### ISSUE TITLE
1 [B5] Dynamically sized data stored in Instance storage

### ISSUE THREAD

**Issue by dkcumming** [soroswap/aggregator#52]
As a general rule, dynamically stored data should not be stored in Instance storage and should be stored in Persistent storage instead. Two reasons that Persistent storage is recommended over Instance storage is that 1. all of Instance storage is read for any call to the contract, even if the dynamic data is not accessed, and 2. there becomes a risk of overflowing the allocated buffer for Instance storage as the dynamic data grows in size. 

[contracts/aggregator/src/storage.rs:72:87](https://github.com/soroswap/aggregator/blob/ed4ce017838ddd4f5c73a8666241c47b55ee1828/contracts/aggregator/src/storage.rs#L72-L87) stores a `Vec<String>` in Instance storage. This vector holds the identifiers for the protocols that can be used to swap assets. It is expected that the number of identifiers stored in this vector is less than 10, and so this should cause negligible overhead for 1. and there should be no risk of 2. (listed above). That being said, there are no guards in the contract itself to protect from the vector growing unbounded, and so this is only enforced by the `Admin` and without consideration it is possible to grow the vector to an inappropriate size.

**Comment by esteblock** [comment]
Dynamically Sized Data in Instance Storage
Severity: Informative Recommended Action: Fix Code Not addressed by client
Description
As a general rule, dynamically stored data should not be stored in Instance storage and should
be stored in Persistent storage instead. Two reasons that Persistent storage is recommended
over Instance storage are:
1. All Instance storage is ready for any call to the contract, even if the dynamic data is not
accessed;
2. There becomes a risk of overflowing the allocated buffer for Instance storage as the
dynamic data grows in size.
The functions responsible for storing and fetching the protocol ids in the aggregator (lines 72 to
87 of the storage module of the Aggregator) specifically use Instance storage to handle a
Vec<String> . This vector holds the identifiers for the protocols that can be used to swap
assets. It is expected that the number of identifiers stored in this vector is less than 10, and so
this should cause negligible overhead for reason number 1, and there should be no risk of
issues related to reason number 2 (listed above). That being said, there are no guards in the
contract itself to protect from the vector growing unbounded, and so this is only enforced by the
Admin, and without consideration, it is possible to grow the vector to an inappropriate size.
Recommendation
When handling data of dynamic size in storage, use Persistent storage instead of Instance.

**Comment by joaquinsoza** [comment]
### **Response to Audit Feedback on Instance Storage for Dynamically Sized Data**

We appreciate the audit team’s recommendation regarding the use of Persistent storage for dynamically sized data instead of Instance storage. However, given the design and expected usage of the Aggregator contract, we believe that Instance storage is appropriate for the following reasons:

- **Minimal Risk:** The Aggregator contract currently manages a small number of adapters. The use of Instance storage for protocol identifiers keeps the risk of storage overflow and performance overhead minimal.
- **Future Flexibility:** If the number of adapters grows significantly in the future, we can upgrade the contract to use Persistent storage. This approach allows us to optimize for current usage while retaining the flexibility to adapt as needed.

We believe that the current use of Instance storage is suitable and does not pose a significant risk, but we remain open to revisiting this decision if circumstances change.
